# Generated by Django 5.0 on 2024-09-23 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                ("amount", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
